//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   eee に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NestedUserControl1_Driver {
            get {
                return ResourceManager.GetString("NestedUserControl1_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   using Codeer.Friendly.Dynamic;
        ///using Codeer.Friendly;
        ///using Codeer.Friendly.Windows;
        ///using Codeer.Friendly.Windows.Grasp;
        ///using Codeer.TestAssistant.GeneratorToolKit;
        ///using RM.Friendly.WPFStandardControls;
        ///using System.Windows.Controls;
        ///
        ///namespace TestCode
        ///{
        ///    [WindowDriver(TypeFullName = &quot;Target.CreateDriverTarget.SingleWindow&quot;)]
        ///    public class SingleWindow_Driver
        ///    {
        ///        public WindowControl Core { get; }
        ///        public WPFTextBox DatePickerTextBox =&gt; new WPFTextBox(Core.VisualTree [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SingleWindow_Driver {
            get {
                return ResourceManager.GetString("SingleWindow_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ccc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TabUserControlWindow_Driver {
            get {
                return ResourceManager.GetString("TabUserControlWindow_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   bbb に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserControl1_Driver {
            get {
                return ResourceManager.GetString("UserControl1_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ddd に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserControl2_Driver {
            get {
                return ResourceManager.GetString("UserControl2_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   aaa に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserControlWindow_Driver {
            get {
                return ResourceManager.GetString("UserControlWindow_Driver", resourceCulture);
            }
        }
    }
}
